"""Shared constants."""

CATEGORIES = "categories"
CATEGORIES_TXT = "categories.txt"
COUNT = "count"
CREATED_AT = "created_at"
DATA = "data"
DESCRIPTION = "description"
DOCUMENTS = "documents"
EMBEDDING_MODEL = "embedding_model"
EMBEDDINGS = "embeddings"
IDS = "ids"
LLM_DESCRIPTION = "llm_description"
METADATA = "metadatas"
NAME = "name"
NARROWING = "narrowing"
NARROWING_STRATEGY = "narrowing_strategy"
NARROWING_TIME_MS = "narrowing_time_ms"
NARROWED_TO = "narrowed_to"
PATH = "path"
SELECTION_TIME_MS = "selection_time_ms"
RESULTS = "results"
SELECTION = "selection"
SRC = "src"
TOTAL_CATEGORIES = "total_categories"
VECTOR_STORE = "vector_store"
VECTOR_STORE_ENABLED = "vector_store_enabled"
