"""Google Gemini API client for image generation."""

from google import genai
from google.genai import types


class GeminiImageGenerator:
    """Handles interactions with Google Gemini API for image generation."""
    
    def __init__(self, api_key: str):
        """
        Initialize the Gemini client.
        
        Args:
            api_key: Google API key for authentication
        """
        self.client = genai.Client(api_key=api_key)
        self.model = "gemini-3-pro-image-preview"
    
    def generate_image(self, prompt: str, base_image_base64: str) -> bytes:
        """
        Generate an image using Gemini API with a base image and prompt.
        
        Args:
            prompt: The formatted prompt for image generation
            base_image_base64: Base64-encoded base image
            
        Returns:
            Raw image bytes from the API response
            
        Raises:
            ValueError: If no image was generated by the API
        """
        response = self.client.models.generate_content(
            model=self.model,
            contents=[
                {
                    "role": "user",
                    "parts": [
                        {"text": prompt},
                        {
                            "inline_data": {
                                "mime_type": "image/png",
                                "data": base_image_base64,
                            }
                        },
                    ],
                }
            ],
            config=types.GenerateContentConfig(
                response_modalities=["TEXT", "IMAGE"]
            ),
        )
        
        # Extract the image from the response
        for part in response.candidates[0].content.parts:
            if part.inline_data is not None:
                return part.inline_data.data
        
        raise ValueError("No image was generated by Gemini")

